apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: k8s-page
  name: k8s-page
  namespace: k8s-club
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-page
  strategy: {}
  template:
    metadata:
      labels:
        app: k8s-page
    spec:
      containers:
      - image: nginx:alpine
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
status: {}
