apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: foo-pod
  name: foo-pod
spec:
  containers:
  - image: registry/test-fe:v1.2
    name: foo-pod
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
