apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: {{ .Values.namespace }}
spec: {}
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.deployName }}
  name: {{ .Values.deployName }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Values.deployName }}
  strategy: {}
  template:
    metadata:
      labels:
        app: {{ .Values.deployName }}
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        name: {{ .Chart.Name }}
        ports:
        - containerPort: {{ .Values.containerPort }}
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.deployName }}
  name: {{ .Values.serviceName }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: {{ .Values.svcPort }}
    protocol: TCP
    targetPort: {{ .Values.containerPort }}
    nodePort: {{ .Values.nodePort }}
  selector:
    app: {{ .Values.deployName }}
  type: NodePort
status:
  loadBalancer: {}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: {{ .Values.ingressName }}
  namespace: {{ .Values.namespace }}
spec:
  ingressClassName: {{ .Values.className }}
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - backend:
          service:
            name: {{ .Values.serviceName }}
            port:
              number: {{ .Values.svcPort }}
        path: /
        pathType: Prefix