apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  myvalue: "Hello from AM Demo"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  myvalue: "Hello from AM Demo"
  drink: {{ .Values.favourite.drink }}
  food: {{ .Values.favourite.food }}