apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.service }}
  name: {{ .Chart.Name }}-{{ .Values.service }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.service }}
  strategy: {}
  template:
    metadata:
      labels:
        app: {{ .Values.service }}
    spec:
      containers:
      - image: registry/{{ .Values.registry.image }}:{{ .Values.registry.tag }}
        name: {{ .Values.service }}
        ports:
        - containerPort: {{ .Values.port }}
        resources: {}
status: {}
