apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-{{ .Values.service }}-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.domain_name }}
    http:
      paths:
      - backend:
          service:
            name: {{ .Chart.Name }}-{{ .Values.service }}-svc
            port:
              number: 30080
        path: /
        pathType: Prefix
status:
  loadBalancer: {}